// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Business.proto
// Protobuf C++ Version: 5.29.0-rc2

#ifndef Business_2eproto_2epb_2eh
#define Business_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Business_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Business_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Business_2eproto;
class Business;
struct BusinessDefaultTypeInternal;
extern BusinessDefaultTypeInternal _Business_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class Business final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Business) */ {
 public:
  inline Business() : Business(nullptr) {}
  ~Business() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Business* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Business));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Business(
      ::google::protobuf::internal::ConstantInitialized);

  inline Business(const Business& from) : Business(nullptr, from) {}
  inline Business(Business&& from) noexcept
      : Business(nullptr, std::move(from)) {}
  inline Business& operator=(const Business& from) {
    CopyFrom(from);
    return *this;
  }
  inline Business& operator=(Business&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Business& default_instance() {
    return *internal_default_instance();
  }
  static inline const Business* internal_default_instance() {
    return reinterpret_cast<const Business*>(
        &_Business_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Business& a, Business& b) { a.Swap(&b); }
  inline void Swap(Business* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Business* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Business* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Business>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Business& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Business& from) { Business::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Business* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Business"; }

 protected:
  explicit Business(::google::protobuf::Arena* arena);
  Business(::google::protobuf::Arena* arena, const Business& from);
  Business(::google::protobuf::Arena* arena, Business&& from) noexcept
      : Business(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLegalAdressFieldNumber = 2,
    kCompanyNameFieldNumber = 3,
    kLineActivityFieldNumber = 4,
    kStockFlotationFieldNumber = 1,
    kForeignEconomicActivityFieldNumber = 5,
  };
  // required string legal_adress = 2;
  bool has_legal_adress() const;
  void clear_legal_adress() ;
  const std::string& legal_adress() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_legal_adress(Arg_&& arg, Args_... args);
  std::string* mutable_legal_adress();
  PROTOBUF_NODISCARD std::string* release_legal_adress();
  void set_allocated_legal_adress(std::string* value);

  private:
  const std::string& _internal_legal_adress() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_legal_adress(
      const std::string& value);
  std::string* _internal_mutable_legal_adress();

  public:
  // required string company_name = 3;
  bool has_company_name() const;
  void clear_company_name() ;
  const std::string& company_name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_company_name(Arg_&& arg, Args_... args);
  std::string* mutable_company_name();
  PROTOBUF_NODISCARD std::string* release_company_name();
  void set_allocated_company_name(std::string* value);

  private:
  const std::string& _internal_company_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_company_name(
      const std::string& value);
  std::string* _internal_mutable_company_name();

  public:
  // optional string line_activity = 4;
  bool has_line_activity() const;
  void clear_line_activity() ;
  const std::string& line_activity() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_line_activity(Arg_&& arg, Args_... args);
  std::string* mutable_line_activity();
  PROTOBUF_NODISCARD std::string* release_line_activity();
  void set_allocated_line_activity(std::string* value);

  private:
  const std::string& _internal_line_activity() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_line_activity(
      const std::string& value);
  std::string* _internal_mutable_line_activity();

  public:
  // required int32 stock_flotation = 1;
  bool has_stock_flotation() const;
  void clear_stock_flotation() ;
  ::int32_t stock_flotation() const;
  void set_stock_flotation(::int32_t value);

  private:
  ::int32_t _internal_stock_flotation() const;
  void _internal_set_stock_flotation(::int32_t value);

  public:
  // optional bool foreign_economic_activity = 5;
  bool has_foreign_economic_activity() const;
  void clear_foreign_economic_activity() ;
  bool foreign_economic_activity() const;
  void set_foreign_economic_activity(bool value);

  private:
  bool _internal_foreign_economic_activity() const;
  void _internal_set_foreign_economic_activity(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Business)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      54, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Business& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr legal_adress_;
    ::google::protobuf::internal::ArenaStringPtr company_name_;
    ::google::protobuf::internal::ArenaStringPtr line_activity_;
    ::int32_t stock_flotation_;
    bool foreign_economic_activity_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Business_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Business

// required int32 stock_flotation = 1;
inline bool Business::has_stock_flotation() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void Business::clear_stock_flotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stock_flotation_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int32_t Business::stock_flotation() const {
  // @@protoc_insertion_point(field_get:Business.stock_flotation)
  return _internal_stock_flotation();
}
inline void Business::set_stock_flotation(::int32_t value) {
  _internal_set_stock_flotation(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:Business.stock_flotation)
}
inline ::int32_t Business::_internal_stock_flotation() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.stock_flotation_;
}
inline void Business::_internal_set_stock_flotation(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stock_flotation_ = value;
}

// required string legal_adress = 2;
inline bool Business::has_legal_adress() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Business::clear_legal_adress() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.legal_adress_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Business::legal_adress() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Business.legal_adress)
  return _internal_legal_adress();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Business::set_legal_adress(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.legal_adress_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Business.legal_adress)
}
inline std::string* Business::mutable_legal_adress() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_legal_adress();
  // @@protoc_insertion_point(field_mutable:Business.legal_adress)
  return _s;
}
inline const std::string& Business::_internal_legal_adress() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.legal_adress_.Get();
}
inline void Business::_internal_set_legal_adress(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.legal_adress_.Set(value, GetArena());
}
inline std::string* Business::_internal_mutable_legal_adress() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.legal_adress_.Mutable( GetArena());
}
inline std::string* Business::release_legal_adress() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Business.legal_adress)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.legal_adress_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.legal_adress_.Set("", GetArena());
  }
  return released;
}
inline void Business::set_allocated_legal_adress(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.legal_adress_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.legal_adress_.IsDefault()) {
    _impl_.legal_adress_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Business.legal_adress)
}

// required string company_name = 3;
inline bool Business::has_company_name() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Business::clear_company_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.company_name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Business::company_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Business.company_name)
  return _internal_company_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Business::set_company_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.company_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Business.company_name)
}
inline std::string* Business::mutable_company_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_company_name();
  // @@protoc_insertion_point(field_mutable:Business.company_name)
  return _s;
}
inline const std::string& Business::_internal_company_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.company_name_.Get();
}
inline void Business::_internal_set_company_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.company_name_.Set(value, GetArena());
}
inline std::string* Business::_internal_mutable_company_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.company_name_.Mutable( GetArena());
}
inline std::string* Business::release_company_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Business.company_name)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.company_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.company_name_.Set("", GetArena());
  }
  return released;
}
inline void Business::set_allocated_company_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.company_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.company_name_.IsDefault()) {
    _impl_.company_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Business.company_name)
}

// optional string line_activity = 4;
inline bool Business::has_line_activity() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void Business::clear_line_activity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.line_activity_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& Business::line_activity() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Business.line_activity)
  return _internal_line_activity();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Business::set_line_activity(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.line_activity_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Business.line_activity)
}
inline std::string* Business::mutable_line_activity() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_line_activity();
  // @@protoc_insertion_point(field_mutable:Business.line_activity)
  return _s;
}
inline const std::string& Business::_internal_line_activity() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.line_activity_.Get();
}
inline void Business::_internal_set_line_activity(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.line_activity_.Set(value, GetArena());
}
inline std::string* Business::_internal_mutable_line_activity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.line_activity_.Mutable( GetArena());
}
inline std::string* Business::release_line_activity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Business.line_activity)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.line_activity_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.line_activity_.Set("", GetArena());
  }
  return released;
}
inline void Business::set_allocated_line_activity(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.line_activity_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.line_activity_.IsDefault()) {
    _impl_.line_activity_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Business.line_activity)
}

// optional bool foreign_economic_activity = 5;
inline bool Business::has_foreign_economic_activity() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void Business::clear_foreign_economic_activity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.foreign_economic_activity_ = false;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline bool Business::foreign_economic_activity() const {
  // @@protoc_insertion_point(field_get:Business.foreign_economic_activity)
  return _internal_foreign_economic_activity();
}
inline void Business::set_foreign_economic_activity(bool value) {
  _internal_set_foreign_economic_activity(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:Business.foreign_economic_activity)
}
inline bool Business::_internal_foreign_economic_activity() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.foreign_economic_activity_;
}
inline void Business::_internal_set_foreign_economic_activity(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.foreign_economic_activity_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Business_2eproto_2epb_2eh
